# Numpy

In [45]:
import numpy as np

np.random.seed(1234)


## Basics

In [46]:
# Scalar
x = np.array([1.3 , 2.2, 1.7])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)


x:  [1.3 2.2 1.7]
x ndim:  1
x shape: (3,)
x size:  3
x dtype:  float64


In [47]:
# add code here
# Matrix
x = np.array([[1,2], [3,4]])
print("x:\n ", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)


x:
  [[1 2]
 [3 4]]
x ndim:  2
x shape: (2, 2)
x size:  4
x dtype:  int64


In [48]:
# add code here
# 3-D Tensor 
x = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print("x:\n ", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:
  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape: (2, 2, 2)
x size:  8
x dtype:  int64


In [49]:
# add code here
# ..

## Indexing

In [74]:
# add code here
x = np.array([1, 1, 3])
print ("x: " , x)
print ("x[0]: ", x[0])
x[0] = 0
print ("x: ", x)

x:  [1 1 3]
x[0]:  1
x:  [0 1 3]


In [75]:
# add code here
# Slicing
x = np.array([[1,2,3,4], [5,6,7,8,], [9,10,11,12]])
print(x)
print("x column 1: ", x[:, 1])
print("x row 0: ", x[0, :])
print("x rows 0,1 & cols 1,2: \n", x[0:2, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1 & cols 1,2: 
 [[2 3]
 [6 7]]


In [52]:
# add code here
# ...

In [76]:
# add code here
# Boolean array
x = np.array([[1,2], [3,4], [5,6]])
print ("x:\n", x)
print("x > 2: \n", x > 2)
print("x[x > 2]: \n", x[ x > 2])

x:
 [[1 2]
 [3 4]
 [5 6]]
x > 2: 
 [[False False]
 [ True  True]
 [ True  True]]
x[x > 2]: 
 [3 4 5 6]


## Arithmetic

In [77]:
# add code here


## Dot product

In [55]:
# add code here
# ...

## Axis Operations

In [56]:
# add code here
# ...

In [57]:
# add code here
# ...

## Broadcasting

In [58]:
# add code here
# ...

## Transpose

In [59]:
# add code here
# ...

## Reshape

In [60]:
# add code here
# ...

## Joining

In [61]:
# add code here
# ...

In [62]:
# add code here
# ...

In [63]:
# add code here
# ...

## Expanding / Reducing

In [64]:
# add code here
# ...

In [65]:
# add code here
# ...

## Arrays vs Lists

In [66]:
# add code here
# ...

In [67]:
# add code here
# ...

In [68]:
# add code here
# ...

# Functions

## Math

In [69]:
# add code here
# ...

In [70]:
# add code here
# ...

## Diagrams

In [71]:
# add code here
# ...

In [72]:
# add code here
# ...

# Derivatives

In [73]:
# add code here
# ...